### ISSUE TITLE
Release new version 0.0.3

### ISSUE THREAD

**Issue by okkez** [kiyoto/fluent-plugin-grok-parser#12]
I've added multiline support #10.
We need new version of this plugin gem.

Can I release new version? @kiyoto 
https://rubygems.org/gems/fluent-plugin-grok-parser

Please add my account as an owner to fluent-plugin-grok-parser gem.
See http://help.rubygems.org/discussions/questions/151-adding-another-owner

My email address is okkez000 at gmail.com

Thanks.

**Comment by kiyoto** [comment]
Done. Please check and thank you for your contribution and patience!

**Comment by okkez** [comment]
@kiyoto Thank you very much!
I will release new version of this plugin later.
