### ISSUE TITLE
Enable TravisCI

### ISSUE THREAD

**Issue by okkez** [kiyoto/fluent-plugin-grok-parser#15]
I added `.travis.yml` but disable TravisCI support.

@kiyoto enable TravisCI, please :bow:

**Comment by okkez** [comment]
ping? @kiyoto

**Comment by kiyoto** [comment]
@okkez Sorry for not noticing this until now. I am setting this up now-ish and will reference this issue there.

Unfortunately, I spend most of my time away from GH these days. If I don't respond to your comments in a couple of days, please ping me on Twitter at @kiyototamura.

**Comment by okkez** [comment]
Thanks!
