### ISSUE TITLE
multiline_grok

### ISSUE THREAD

**Issue by fahimeh2010** [kiyoto/fluent-plugin-grok-parser#18]
Hello
First thank you for your open source project.

I use fluent-plugin-grok-parser. my configuration is like this:
<source>
  @type tail
  path /var/log/error.log
  format multiline_grok
  grok_pattern %{IP:ip_address}\n%{GREEDYDATA:message}
  multiline_start_regexp /^\s/
  tag grokked_log
</source>

<match **>
    type               stdout
</match>

and my log file(/var/log/error.log) is like this:
1.2.3.4
client address

I just got this warning in td-agent and it does not parse the log file.
got incomplete line before first line from
there is no parsed log

Thanks a lot

**Comment by okkez** [comment]
Show me the warning messages, please.
I cannot understand your issue.

**Comment by fahimeh2010** [comment]
Hello
Thanks for your reply.

`<source>`
    `  @type tail `
`  path /var/log/error.log`
 ` format multiline_grok`
`  grok_pattern %{IP:ip_address}\n%{GREEDYDATA:message}`
`  multiline_start_regexp /^\s/`
`  tag grokked_log`
`</source>`
`<match **>`
`    @type stdout`
`</match>`


if /var/log/error.log exists I just got this warning message and no parsed message

2016-08-17 10:14:12 +0430 [warn]: got incomplete line before first line from /var/log/error.log: "12.36.58.232\n"
2016-08-17 10:14:12 +0430 [warn]: got incomplete line before first line from /var/log/error.log: "yyyyyyy\n"
2016-08-17 10:14:12 +0430 fluent.warn: {"message":"got incomplete line before first line from /var/log/error.log: \"12.36.58.232\\n\""}
2016-08-17 10:14:12 +0430 fluent.warn: {"message":"got incomplete line before first line from /var/log/error.log: \"yyyyyyy\\n\""}


and if i just create /var/log/mysql, I got no warning and no parsed message

Thanks a lot

**Comment by okkez** [comment]
Maybe your configuration comes from sample configuration in README.md.
But README.md is wrong....

```
<source>
  @type tail
  path /var/log/error.log
  format multiline_grok
  grok_pattern %{IP:ip_address}%{GREEDYDATA:message}
  multiline_start_regexp /^[^\s]/
  tag grokked_log
</source>
<match **>
  @type stdout
</match>
```

* `grok_pattern %{IP:ip_address}%{GREEDYDATA:message}`
  * `\n` will be escaped and cannot match new line
* `multiline_start_regexp /^[^\s]/`
  * `/^\s/` means that multiline starts with white space

I will fix example on README.md.

**Comment by fahimeh2010** [comment]
Hello 
Thanks a lot for reply.
I want to set multiline_start_regexp with something like this:(for php-error)
(Stack trace:)|(^#.+)|(^\"\")|(  thrown+)|(^\s)

i use this config
`multiline_start_regexp /^[(Stack trace:)]|^[(^#.+)]|^[(^\"\")]|^[(  thrown.+)]|^[(^\s)]/` 
but I can not get the proper result.

Could you please help me?

Thank a lot

**Comment by fahimeh2010** [comment]
grok_pattern is something like this
`grok_pattern \[%{GREEDYDATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}`

**Comment by okkez** [comment]
Please show me concrete logs. I'm not using PHP, so I don't know PHP stack trace at all.

But I think, `multiline_start_regexp /^Stack trace:/` is enough for your situation, maybe.
And you should consider grok_pattern more carefully.

This plugin bundles many patterns under https://github.com/kiyoto/fluent-plugin-grok-parser/tree/master/patterns

**Comment by fahimeh2010** [comment]
One of like  file is like this:

[01-Jun-2016 12:16:26 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171
Stack trace:
#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)
#1 /var/www/website/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)
#2 /var/www/website/includes/database/select.inc(1265): DatabaseConnection->query('SELECT w.*\nFROM...', Array, Array)
#3 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.module(709): SelectQuery->execute()
#4 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.worker.inc(278): pt_cron2_load_worker('14')
#5 [internal function]: pt_cron2_worker_shutdown('14', 1464766262)
#6 {main}
  thrown in /var/www/website/includes/database/database.inc on line 2171

I will appreciate if you would help.

Thanks a lot

**Comment by okkez** [comment]
fluent.conf is following.

```
<source>
  @type tail
  path a.log
  pos_file /tmp/a.pos
  #format grok
  format multiline_grok
  grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
  multiline_start_regexp /PHP Fatal error:/
  read_from_head true
  tag grokked_log
</source>

<filter **.*>
  @type stdout
</filter>

<match **.*>
  @type file
  path /tmp/x.log
</match>
```

I pasted following log to a.log twice.

```
[01-Jun-2016 12:16:26 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171
Stack trace:
#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)
#1 /var/www/website/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)
#2 /var/www/website/includes/database/select.inc(1265): DatabaseConnection->query('SELECT w.*\nFROM...', Array, Array)
#3 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.module(709): SelectQuery->execute()
#4 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.worker.inc(278): pt_cron2_load_worker('14')
#5 [internal function]: pt_cron2_worker_shutdown('14', 1464766262)
#6 {main}
  thrown in /var/www/website/includes/database/database.inc on line 2171
```

I got following result.

```
2016-08-18 17:55:53 +0900 grokked_log: {"raw_timestamp":"01-Jun-2016 12:16:26 UTC","name":"PHP","loglevel":"Fatal","message":"error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\nStack trace:\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)\n#1 /var/www/website/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)\n#2 /var/www/website/includes/database/select.inc(1265): DatabaseConnection->query('SELECT w.*\\nFROM...', Array, Array)\n#3 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.module(709): SelectQuery->execute()\n#4 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.worker.inc(278): pt_cron2_load_worker('14')\n#5 [internal function]: pt_cron2_worker_shutdown('14', 1464766262)\n#6 {main}\n  thrown in /var/www/website/includes/database/database.inc on line 2171\n"}
```

**Comment by fahimeh2010** [comment]
Hello 
Thank you very much
my config is like this:
`<filter *.*.*.*.php>`
 `   @type parser`
    ` format multiline_grok`
   ` grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}`
 `   multiline_start_regexp /PHP Fatal error:/`
`  key_name message`
 `</filter>`
 but it does not work with the above log file.

**Comment by fahimeh2010** [comment]
```
<filter *.*.*.*.php>
    @type parser
    format multiline_grok
    grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
     multiline_start_regexp /(Stack trace:)|(^#+)|(^\"\")|(  thrown+)|(^\s)/
     reserve_data yes
   key_name message
</filter>

```
even the above config did not work.
Could you please help me?

**Comment by okkez** [comment]
Why do you use multiline_grok with filter parser plugin?
Could you describe what do you want to do?

**Comment by fahimeh2010** [comment]
I want to parse php log that I receive in fluentd. I use fluentd-agent-hydra in clients to send log file to fluentd. 
```
<source>
  @type forward
   port 25569
</source>
<filter *.*.*.*.php>
    @type parser
    format multiline_grok
    grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
     multiline_start_regexp /(Stack trace:)|(^#+)|(^\"\")|(  thrown+)|(^\s)/
     reserve_data yes
   key_name message
</filter>
<match **>
  @type elasticserch
   ....
   ....
</match>
```
what can I use instead of fluentd parser plugin(https://github.com/tagomoris/fluent-plugin-parser)?
or multiline_grok does not work in the parser plugin?

Thanks a lot

**Comment by okkez** [comment]
`multiline_start_regexp /(Stack trace:)|(^#+)|(^\"\")|(  thrown+)|(^\s)/` is totally wrong.
Because in\_forward receives one event and delegate it to filter\_parser as is.
The event includes multiline log in a field, I think.

I testes following configuration. It works.

```
<source>
  @type dummy
  dummy {"message": "[01-Jun-2016 12:16:26 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\nStack trace:\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)\n#1 /var/www/website/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)\n#2 /var/www/website/includes/database/select.inc(1265): DatabaseConnection->query('SELECT w.* FROM...', Array, Array)\n#3 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.module(709): SelectQuery->execute()\n#4 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.worker.inc(278): pt_cron2_load_worker('14')\n#5 [internal function]: pt_cron2_worker_shutdown('14', 1464766262)\n#6 {main}\n  thrown in /var/www/website/includes/database/database.inc on line 2171"}
  tag dummy.log
</source>

<filter **.*>
  @type parser
  key_name message
  #format grok
  format multiline_grok
  grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
</filter>

<filter **.*>
  @type stdout
</filter>

<match **.*>
  @type file
  path /tmp/x.log
</match>
```

I got following result.

```
2016-08-22T13:20:22+09:00       dummy.log       {"raw_timestamp":"01-Jun-2016 12:16:26 UTC","name":"PHP","loglevel":"Fatal","message":"error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: Gen
eral error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\nStack trace:\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)\n#1 /var
/www/website/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)\n#2 /var/www/website/includes/database/select.inc(1265): DatabaseConnection->query('SELECT w.* FROM...', Array, Arra
y)\n#3 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.module(709): SelectQuery->execute()\n#4 /var/www/website/sites/all/modules/partotech/cron2/pt_cron2.worker.inc(278): pt_cron2_load_worker('14')\
n#5 [internal function]: pt_cron2_worker_shutdown('14', 1464766262)\n#6 {main}\n  thrown in /var/www/website/includes/database/database.inc on line 2171"}
```

**Comment by fahimeh2010** [comment]
oh I got no proper result.
```
<source>
  @type forward
   port 25569
</source>
<filter *.*.*.*.php>
    @type parser
     key_name message
    format multiline_grok
    grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
</filter>
<match **>
  @type elasticserch
   ....
   ....
</match>
```
with the log file like this:
```
echo -e "[01-Jun-2016 12:16:26 ] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\nStack trace:\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)" >> php.log
```
the result:
```
2016-08-22 09:13:38 +0430 bella.bella.php: {"loglevel":"Fatal","name":"PHP","message":"error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171","type":"php","raw_timestamp":"01-Jun-2016 12:16:26"}
```

**Comment by fahimeh2010** [comment]
Actually I have the similar problem https://groups.google.com/forum/#!topic/fluentd/3BdUTL9dzPw

**Comment by okkez** [comment]
Try following configuration.
You can check received events format.

```
<source>
  @type forward
   port 25569
</source>
<filter *.*.*.*.php>
   @type stdout
</filter>
<filter *.*.*.*.php>
    @type parser
     key_name message
    format multiline_grok
    grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
</filter>
<match **>
  @type elasticserch
   ....
   ....
</match>
```

**Comment by fahimeh2010** [comment]
with this log
```
echo -e "[01-Jun-2016 12:16:26 ] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\nStack trace:\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)" >> php.log
```
I got the below result:
```
2016-08-22 09:45:14 +0430 bella.bella.php: {"message":"[01-Jun-2016 12:16:26 ] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171"}
2016-08-22 09:45:14 +0430  bella.bella.php: {"message":"Stack trace:"}
2016-08-22 09:45:14 +0430  bella.bella.php: {"message":"#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)"}
2016-08-22 09:45:14 +0430 bella.bella.php: {"loglevel":"Fatal","name":"PHP","message":"error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171","type":"php""raw_timestamp":"01-Jun-2016 12:16:26"}
```
so it actually got the message line by line not whole of it.

**Comment by fahimeh2010** [comment]
is there a way to correct it?

**Comment by okkez** [comment]
Some solutions:

1. Use in_tail and multiline_grok instead of fluent-agent-hydra
  * :heavy_plus_sign: very simple
  * :heavy_minus_sign: need more resource
2. Use [fluent-plugin-concat](https://github.com/okkez/fluent-plugin-concat) before filter_parse
  * :heavy_minus_sign: a little difficult
  * :heavy_minus_sign: consider timeout error
3. Concatenate logs before fluent-agent-hydra
  * I don't know

I recommend solution 1.

For example solution 2:

```
<source>
  @type forward
   port 25569
</source>
<filter *.*.*.*.php>
   @type concat
  key message
  multiline_start_regexp /PHP Fatal error:/
</filter>
<filter *.*.*.*.php>
    @type parser
     key_name message
    format multiline_grok
    grok_pattern \[%{DATA:raw_timestamp}\] %{DATA:name} %{WORD:loglevel} %{GREEDYDATA:message}
</filter>
<match **>
  @type elasticserch
   ....
   ....
</match>
```

**Comment by fahimeh2010** [comment]
I suggest something  in fluent-plugin-concat (I do not know it is possible or not), consider n_lines as at most lines not just exact the number of it.

yes I got this error

```
"error_class":"Fluent::ConcatFilter::TimeoutError","record":{"message":"[01-Jun-2016 12:16:26] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\nStack trace:\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)"},"tag":"bella.bella.php","time":1471844660,"error":"Timeout flush: bella.bella.php:default","message":"dump an error event: error_class=Fluent::ConcatFilter::TimeoutError error=\"Timeout flush: bella.bella.php:default\" tag=\"bella.bella.php\" time=1471844660 record={\"message\"=>\"[01-Jun-2016 12:16:26] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/website/includes/database/database.inc:2171\\nStack trace:\\n#0 /var/www/website/includes/database/database.inc(2171): PDOStatement->execute(Array)\"}"}
2016-08-22 10:14:20 +0430 bella.bella.php: {"message":"Timeout flush: bella.bella.php:default"}
```
but it worked

**Comment by okkez** [comment]
Could you close this issue, if this issue is resolved?

**Comment by fahimeh2010** [comment]
for one line php log there is no log until the timeout error and after that I can get one line log

**Comment by okkez** [comment]
See https://github.com/okkez/fluent-plugin-concat/issues/9

**Comment by fahimeh2010** [comment]
the log is not started with PHP Fatal error:
like: 
```
[28-May-2016 12:30:38 ] PHP Notice:  Undefined index: HTTP_X_FORWARDED_FOR in /var/www/website/test.php on line 13
```

**Comment by okkez** [comment]
```
<filter *.*.*.*.php>
   @type concat
  key message
  multiline_start_regexp /PHP (Notice|Fatal error):/
</filter>
```

**Comment by fahimeh2010** [comment]
so I should know all log levels,
Thank you very much
