### ISSUE TITLE
parse failed undefined method `parse' for #<String:

### ISSUE THREAD

**Issue by jslusher** [kiyoto/fluent-plugin-grok-parser#19]
Not sure which of the plugins is the culprit, so I'll raise the issue in both and hopefully I can get pointed in the right direction. I'm trying to use the grok-parser plugin to format logs captured with the parser plugin to grok elasticsearch slowlogs. Here is the test configuration:

    <source>
      @type dummy
      dummy {"log":"[2016-08-21 18:02:29,649][WARN ][index.search.slowlog.fetch] [logstash-2016.08.21]took[3s], took_millis[3080], types[], stats[], search_type[QUERY_AND_FETCH], total_shards[1], source[{\"size\":500,\"sort\":[{\"@timestamp\":{\"order\":\"desc\",\"unmapped_type\":\"boolean\"}}],\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}},\"filter\":{\"bool\":{\"must\":[{\"range\":{\"@timestamp\":{\"gte\":1471801647542,\"lte\":1471802547542,\"format\":\"epoch_millis\"}}}],\"must_not\":[]}}}},\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}},\"require_field_match\":false,\"fragment_size\":2147483647},\"aggs\":{\"2\":{\"date_histogram\":{\"field\":\"@timestamp\",\"interval\":\"30s\",\"time_zone\":\"America/Chicago\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1471801647541,\"max\":1471802547542}}}},\"fields\":[\"*\",\"_source\"],\"script_fields\":{},\"fielddata_fields\":[\"@timestamp\"]}], extra_source[], \n","stream":"stdout","time":"2016-08-21T18:02:29.650016637Z"}
      tag dummy-data
    </source>

    <filter dummy-data>
      @type parser
      format grok
      <grok>
        grok_pattern %{ESINDEXSEARCHSLOWLOGS}
        custom_pattern_path /opt/fluentd/grok-patterns
      </grok>
      key_name log
    </filter>
    
    <match dummy-data>
      type stdout
    </match>

I'm getting this error in the output of fluentd:
```[warn]: parse failed undefined method `parse' for #<String:0x0000000329d3c8>```

**Comment by okkez** [comment]
Use `pattern` instead of `grok_pattern` in `<grok>` section.

```
  <grok>
    pattern %{ESINDEXSEARCHSLOWLOGS}
    custom_pattern_path /opt/fluentd/grok-patterns
  </grok>
```

**Comment by jslusher** [comment]
That was the problem. Thanks!
