### ISSUE TITLE
Add support for multiline

### ISSUE THREAD

**Issue by thucatebay** [kiyoto/fluent-plugin-grok-parser#6]
Just like in logstash.

**Comment by moebiuseye** [comment]
I'm voting for this.

**Comment by kiyoto** [comment]
Got it. Any preferred config parameters? Most likely, I'd add an optional field that says something like `multiline_start_regexp` or something.

**Comment by repeatedly** [comment]
What does 'just like' mean?
It means `multiline` codes?

**Comment by kiyoto** [comment]
@thucatebay ping?

**Comment by thucatebay** [comment]
Here's the documentation for logstash multiline filter:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-multiline.html

@kiyoto `multiline_start_regexp` sounds good.

**Comment by okkez** [comment]
Merged #10
